apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: gnb
  annotations:
    metallb.universe.tf/address-pool: custom-addresspool
spec:
  type: LoadBalancer
  ports:
  - name: gnb-ue
    port: 4997
    protocol: UDP
  - name: gnb-upf
    port: 2152
    protocol: UDP
  clusterIP: ""
  publishNotReadyAddresses: true
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: gnb
