apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  namespace: default
spec:
  selector:
    app: open5gs-amf
  ports:
    - protocol: TCP
      port: 38412
      targetPort: 38412
      nodePort: 30012
  type: NodePort
