namespace: your-namespace
phpImage:
  repository: my-php-app
  tag: 1.0.0
nginxImage:
  repository: nginx
  tag: 1.7.9
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  whitelist: "192.168.137.137/32,10.1.198.1/24" # Match this key with the template
  host: my-php-app.local  # This should match the template's expectation
  #tlsSecret: my-php-app-tls  # Ensure this matches the key in the template

