services:
  landing-page:
    build: .
    ports:
      - "80:80"
    container_name: 5g-playground-landing-page
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./challenge-files:/usr/share/nginx/html/challenge-files:ro
    networks:
      - 5g-playground-network

networks:
  5g-playground-network:
    driver: bridge 