apiVersion: v1
kind: Service
metadata:
  name: phpfpm-nginx-service
  namespace: {{ .Values.namespace }}
  labels:
    app: phpfpm-nnginx
spec:
  selector:
    app: phpfpm-nnginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
