apiVersion: v1
kind: Service
metadata:
  name: phpfpm-nginx-service
  labels:
    app: phpfpm-nnginx
spec:
  selector:
    app: phpfpm-nnginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
